### 授权码模式
### 第一步申请授权码(浏览器请求)
# /oauth/authorize?client_id=XcWebApp&response_type=code&scope=all&redirect_uri=http://www.xuecheng-plus.com
### 第二步申请令牌
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=authorization_code&code=xLHNKB&redirect_uri=http://www.xuecheng-plus.com


### 密码模式
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username=diana&password=123456


###校验jwt令牌
POST {{auth_host}}/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjb21wYW55SWRcIjpcIjEyMzIxNDE0MjVcIixcImNyZWF0ZVRpbWVcIjpcIjIwMjItMDktMjhUMDg6MzI6MDNcIixcImlkXCI6XCI1MlwiLFwibmFtZVwiOlwiTeiAgeW4iFwiLFwicGVybWlzc2lvbnNcIjpbXSxcInNleFwiOlwiMVwiLFwic3RhdHVzXCI6XCJcIixcInVzZXJuYW1lXCI6XCJ0MVwiLFwidXR5cGVcIjpcIjEwMTAwMlwifSIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2NzYxMzAwMTgsImF1dGhvcml0aWVzIjpbInhjX3RlYWNobWFuYWdlcl9jb3Vyc2VfYmFzZSIsInhjX3RlYWNobWFuYWdlcl9jb3Vyc2VfZGVsIiwieGNfdGVhY2htYW5hZ2VyX2NvdXJzZV9saXN0IiwieGNfdGVhY2htYW5hZ2VyX2NvdXJzZV9wbGFuIiwieGNfdGVhY2htYW5hZ2VyX2NvdXJzZSIsImNvdXJzZV9maW5kX2xpc3QiLCJ4Y190ZWFjaG1hbmFnZXIiLCJ4Y190ZWFjaG1hbmFnZXJfY291cnNlX21hcmtldCIsInhjX3RlYWNobWFuYWdlcl9jb3Vyc2VfcHVibGlzaCIsInhjX3RlYWNobWFuYWdlcl9jb3Vyc2VfYWRkIl0sImp0aSI6ImE4ZWVhNDcwLTk4NWYtNDRhYi04ZTg5LWI0NTU5NmFiMTA0YyIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.onO96wB5wErnYUeyWzolRKdwcjcxeLnKQDIvGmQ4G-Q


### 资源访问 --加密后不带令牌
GET http://localhost:63040/content/course/2

### 资源访问 --加密后 携带JWT令牌
GET http://localhost:63040/content/course/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJiaXJ0aGRheVwiOlwiMjAyMy0wMi0wMVQxMToxNzowN1wiLFwiY2VsbHBob25lXCI6XCIxMjM0NTZcIixcImNvbXBhbnlJZFwiOlwiMTIzMjE0MTQyNVwiLFwiY3JlYXRlVGltZVwiOlwiMjAyMy0wMi0xMVQxMDoxNTowMFwiLFwiaWRcIjpcIjUzXCIsXCJuYW1lXCI6XCLlrabnlJ8yXCIsXCJuaWNrbmFtZVwiOlwi5YeJ5YawXCIsXCJxcVwiOlwiMTIzNDU2XCIsXCJzZXhcIjpcIjFcIixcInN0YXR1c1wiOlwiMVwiLFwidXNlcm5hbWVcIjpcImRpYW5hXCIsXCJ1dHlwZVwiOlwiMTAxMDAyXCJ9Iiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY3NjA5MzY3NiwiYXV0aG9yaXRpZXMiOlsidGVzdCJdLCJqdGkiOiI1ZjQ2MmEwMy00Mzk3LTQzYzQtOTg0MS1lYjAyZjBmNTlkNjkiLCJjbGllbnRfaWQiOiJYY1dlYkFwcCJ9.09Af5-96RT0CK-WKMufsYEEHna8Yj86aw0HJf8bqSsI

### 网关资源访问
GET http://localhost:63010/content/course/2
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2NzYwNDExNDMsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6Ijg4NWEwNDIyLWI3ODQtNDg2Zi04OTE0LTg5ODcyYTQ0ZWY4YyIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.qDOacmLEB8O2SbsEY-P152JN1FKRD-Ok9HcdM6qfyaM

### 统一认证入口后的 密码登陆
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username={"username":"itcast","authType":"password","password":"111111"}

### 注册
POST {{auth_host}}/auth/register

### 登陆
GET http://localhost:63070/auth/login-success